- src/layout/components/Sidebar/index.vue
> 解决叠模式下左侧不能点击问题

- src/components/chaofan/commentItem.vue
- src/router/index.js
[issue 回复评论时没有表情#91](https://github.com/www-chao-fun/chaofun-front/issues/91) 修复
> 修复-回复评论时没有表情 #91，同时添加取消回复按钮

- src/components/chaofan/commentItem.vue
- src/views/list/articleDetail.vue
> 添加评论和回复评论输入框focus是黏贴图片直接上传

- src/views/submit/submit.vue
fix www-chao-fun/chaofun-front#102
> web点击发帖后标题框自动输入聚焦

- babel.config.js
- package.json
- src/components/chaofan/ListItem.vue
- src/components/chaofan/ListItemWidth.vue
- src/components/chaofan/SimListItem.vue
- src/components/chaofan/commentItem.vue
- src/components/chaofan/component/itemTopTitle.vue
- src/components/chaofan/trends.vue
- src/layout/components/chat/chat.vue
- src/main.js
- src/mixins/mixins.js
- src/views/chat/chatpage.vue
- src/views/list/articleDetail.vue
- src/views/submit/submit.vue
- vue.config.js
> feat: 个性化时间详情页支持点击切换

- README.md
- package.json
- src/components/Submit/CollectionSelector.vue
- src/components/Submit/Editor.vue
- src/components/Submit/TagSelector.vue
- src/components/Submit/UploadList.vue
- src/components/Submit/UploadVideo.vue
- src/components/Submit/Uploader.vue
- src/components/Uploader/index.vue
- src/router/index.js
- src/settings.js
- src/styles/index.scss
- src/utils/exif-check.js
- src/views/submit/submit.vue
- src/views/submit/v2.vue
> 新版发帖中心灰度测试

- src/components/Submit/CollectionSelector.vue
- src/components/Submit/Editor.vue
- src/components/Submit/TagSelector.vue
- src/components/Submit/Uploader.vue
- src/views/submit/v2.vue
fix www-chao-fun/chaofun-front#131 @cijianzy
> fix: 修复新版编辑器

- src/views/list/articleDetail.vue
> fix: 列表页缓存问题

- src/components/chaofan/component/itemArticle.vue
> fix: 多端文本显示不一致

- src/api/api.js
- src/components/Submit/Editor.vue
- src/views/submit/v2.vue
> fix: 发帖相关问题

- src/components/chaofan/component/itemTopTitle.vue
fix：在帖子列表点击帖子的发布时间时，会触发父组件的事件的bug
> fix：在帖子列表点击帖子的发布时间时，会触发父组件的事件的bug

- src/api/api.js
- src/components/chaofan/commentItem.vue
[评论高亮功能实现](https://github.com/www-chao-fun/chaofun-front/issues/199)
> 评论高亮 issues:199

- src/components/chaofan/commentItem.vue
fix：[pull 203](https://github.com/www-chao-fun/chaofun-front/pull/203#issuecomment-1005625307)
> fix：帖子评论点赞数 减小高度并垂直居中

- src/views/list/articleDetail.vue
增加帖子滚动条宽度 [issues #193](https://github.com/www-chao-fun/chaofun-front/issues/193)
> issues #193 帖子滚动条宽度增加到8px

- src/router/index.js
- src/views/list/fbi.vue
- src/views/list/my.vue
- src/views/list/user.vue
issues #210
他人主页显示粉丝数、关注数
我的主页显示个人信息（包含粉丝数、关注数、FBI等）
点击粉丝数、关注数可切换到关注X的、X关注的
调整我的主页部分字体、位置、描述、顺序等使与他人主页、app保持一致
> 我的主页、他人主页修改

- src/api/api.js
- src/views/chaofun-webview/badge/badgeDetail.vue
- src/views/list/my.vue
- src/views/list/user.vue
issues #215 我的主页和他人主页显示徽章
效果图如下：
> issues #215 我的主页和他人主页显示徽章

- src/views/list/setting.vue
> 设置个性签名 长度限制修改为200个字符

- src/views/list/articleDetail.vue
- src/views/list/setting.vue
个人比较习惯按评论顺序排序，所以考虑新增此功能。
设置入口：
点击网页右上角 - 设置 - 本地设置
设置方式如下：
> 帖子评论排序方式可设置

- src/views/list/articleDetail.vue
可滚动至顶部、评论、底部，并设置了对应的快捷键F1、F2、F3
效果图如下：
> 帖子详情新增滚动按钮

- src/components/chaofan/commentItem.vue
- src/views/list/articleDetail.vue
> 新增只看一级评论功能 issues #234

- src/components/chaofan/commentItem.vue
- src/views/list/setting.vue
> fix:  ipad 设置页有个适配问题

- package-lock.json
- src/main.js
> image lazyload 

- src/views/activity/forumRank.vue
- src/views/chaofun-webview/activity/forumRank.vue
> 改正了上次修改时的错别字

- src/api/api.js
- src/components/chaofan/ListItemWidth.vue
- src/components/chaofan/commentItem.vue
- src/components/chaofan/component/itemTopTitle.vue
- src/components/chaofan/noticeItemImages.vue
- src/components/report/report.vue
- src/views/list/articleDetail.vue
举报和复制链接默认隐藏，需要通过入口开启
- 新增举报功能
- 新增复制评论链接功能
*方便使用链接分享或举报*
> feat：新增举报功能

- src/api/api.js
- src/utils/chatJoin.js
- src/views/list/user.vue
- src/views/newChat/chat.vue
> feat:新增单聊入口

- src/components/chaofan/commentItem.vue
在我的评论中item.vote传的是null，需要加上非空判断
> 修复「TA的评论」中点赞反应不对  fix: #316

- src/views/submit/v2.vue
> feat: #308
